### PR TITLE
SW SPI arbitrary width

### PR DESCRIPTION
**Pull request by bazarovdev**
Created PR to make it easier see all changes in one place and maybe receive some useful comments.

There are a lot of work more to be merged into main repository (tests, documentation etc).
For now, I don't see any interest in this by somebody so haven't speeded up, but it is still in my TODO and wasn't dropped. so might happen.
I've divided it into few steps :
1. SPI interface change to support arbitrary bits width 
2. Adding driver for Geeetech's A10M/T printers display that requires 9-bits SPI support
3. Adding Geeetechs configs for Klipper

### CODE REVIEW

**Comment by shadow7412** [comment]
Is this supposed to be targeting the klipper repository, rather than your own master branch?

**Comment by bazarovdev** [comment]
> Is this supposed to be targeting the klipper repository, rather than your own master branch?

Updated description, it is in un-mergable state yet so no mistake here:) Thanks for interest.

**Comment by nwash57** [comment]
Just wanted to register my interest in this... Let me know if there's possibly anything I can help with?
I've been working on getting an A10T running with klipper and the LCD is one of the last things to work out. 

Unrelated: Not sure if you've figured out the color mixing yet but I have an M163/164 emulation macro that handles 3 extruders and seems solid if you're interested.

**Comment by shadow7412** [comment]
Same TBH. Klipper has definitely made a positive impact on my printer in general, but my computer isn't right next to the printer (and octoprint is pretty meh on mobile).

**Comment by bazarovdev** [comment]
Actually, I'm new to Klipper and stuck on each step:
1. hard to find config (thanks to https://github.com/ArmJo/Geeetech-A10-Klipper-GT2560v3-modded for reference to start)
1. not working display (naivly thinking that it will be easy fix, at the end this PR is a possible solution)
1. no PC near 3d printer - tried to run klipper on smart IP camera, created few recepies for Yocto to generate image with linux, Klipper, Moonraker and Mainsail. At the end it is still requires some thinking how to organzie configs in Yocto and solve another configuration issues (like: by default, generated image was using `root` user but Moonraker gives warnings on it) https://github.com/bazarovdev/meta-klipper/pull/1

So for now, I have Raspberry Pi 4 and MainsailOS image to learn how it is organized.
Moved in January to a new place and now I can put 3d printer near PC for easier development.

So, will finish configuring printer to work with RPi and then back to work on merging this PR.

@nwash57 sorry for slow reply, will be happy to see your macros. BTW, I also saw that there is a PR that stuck on review for mixing extruders https://github.com/Klipper3d/klipper/pull/5960

**Comment by bazarovdev** [comment]
Working on new PR:
https://github.com/bazarovdev/klipper/pull/2

**Comment by bazarovdev** [comment]
@shadow7412 @nwash57 
Hi guys, when this PR is merged, it will be possible to add dispaly driver and reference config in next PR.
https://github.com/Klipper3d/klipper/pull/6633
maybe you can review or display interest in it to speed up the merging.

**Comment by bazarovdev** [comment]
@shadow7412 @nwash57 
starting this December 2nd you can use mainline klipper (https://github.com/Klipper3d/klipper/pull/6639)
just update it (pull `master` branch) and modify config to match:

```
# for GT2560V4.1B with 12pin flat cable toward the display YHCB2004-06 ver3.0
# the aip31068_spi driver was added to Klipper on 2024-12-02, commit aecb29d2
[display]
lcd_type: aip31068_spi
latch_pin: PE3
spi_software_sclk_pin: PD0
spi_software_mosi_pin: PC1
spi_software_miso_pin: PH7 # any unused pin
encoder_pins: ^PH0, ^PH1
click_pin: ^!PD2
```

if you have references/manuals how you use M163/M164 macros, I will be happy if you share it here:
https://github.com/Klipper3d/klipper/pull/6767

**Pull request closed without merging**
